/**
 * aicredits-footer.ts
 *
 * Custom pi footer showing accumulated AiCredits usage for the session.
 *
 * Why: pi's default footer shows USD cost from the provider price table, but
 * we're billed in AiCredits, where rates differ from Anthropic/OpenAI list.
 * This extension computes credits-per-message from the live token counts so
 * we can see the real cost in real time.
 *
 * Per-model rates (per 1,000,000 tokens):
 *   input        - first-seen prompt content
 *   cacheRead    - reused cached prompt content (usually ~10x cheaper)
 *   cacheWrite   - tokens written to the prompt cache (usually ~1.25x input)
 *   output       - tokens generated by the model
 *
 * Defaults match the published AiCredits rates for claude-opus-4.7 (500/50/625/2500).
 * Override per model via env var AICREDITS_RATES, JSON shaped:
 *   { "<modelId or glob>": { "input": N, "cacheRead": N, "cacheWrite": N, "output": N } }
 * Example:
 *   AICREDITS_RATES='{"claude-opus-4.7":{"input":500,"cacheRead":50,"cacheWrite":625,"output":2500},
 *                     "claude-haiku-4.5":{"input":80,"cacheRead":8,"cacheWrite":100,"output":400}}'
 *
 * Footer line format (right side):
 *   ↑<input> R<cacheRead> W<cacheWrite> ↓<output>  C<credits>  <model> (<branch>)
 *
 * Usage: just drop in ~/.pi/agent/extensions/ and pi auto-loads it. Toggle with /credits-footer.
 */

import type { AssistantMessage } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { truncateToWidth, visibleWidth } from "@earendil-works/pi-tui";

type Rate = { input: number; cacheRead: number; cacheWrite: number; output: number };

const DEFAULT_RATES: Record<string, Rate> = {
	// AiCredits per 1M tokens, per the user's billing sheet
	"claude-opus-4.7": { input: 500, cacheRead: 50, cacheWrite: 625, output: 2500 },
	"claude-sonnet-4.7": { input: 150, cacheRead: 15, cacheWrite: 188, output: 750 },
	"claude-haiku-4.5": { input: 80, cacheRead: 8, cacheWrite: 100, output: 400 },
	// Generic fallback (used when no entry matches)
	"*": { input: 100, cacheRead: 10, cacheWrite: 125, output: 500 },
};

function loadRates(): Record<string, Rate> {
	const merged = { ...DEFAULT_RATES };
	const env = process.env.AICREDITS_RATES;
	if (!env) return merged;
	try {
		const parsed = JSON.parse(env) as Record<string, Partial<Rate>>;
		for (const [k, v] of Object.entries(parsed)) {
			merged[k] = { ...(merged[k] ?? merged["*"]), ...v } as Rate;
		}
	} catch (e) {
		// silently ignore - default rates still apply
	}
	return merged;
}

function rateFor(rates: Record<string, Rate>, modelId: string | undefined): Rate {
	if (!modelId) return rates["*"];
	if (rates[modelId]) return rates[modelId];
	// loose match: any key that's a prefix of modelId (so "claude-opus-4.7-thinking" matches "claude-opus-4.7")
	for (const k of Object.keys(rates)) {
		if (k !== "*" && modelId.startsWith(k)) return rates[k];
	}
	return rates["*"];
}

function fmt(n: number): string {
	if (n < 1000) return `${n}`;
	if (n < 1_000_000) return `${(n / 1000).toFixed(1)}k`;
	return `${(n / 1_000_000).toFixed(2)}M`;
}

function fmtCredits(c: number): string {
	if (c < 1) return c.toFixed(3);
	if (c < 100) return c.toFixed(2);
	return c.toFixed(0);
}

export default function (pi: ExtensionAPI) {
	const rates = loadRates();
	// On by default - this is the whole point of installing the extension.
	let enabled = true;

	const renderFooter = (ctx: any) => {
		ctx.ui.setFooter((tui: any, theme: any, footerData: any) => {
			const unsub = footerData.onBranchChange(() => tui.requestRender());
			return {
				dispose: unsub,
				invalidate() {},
				render(width: number): string[] {
					let input = 0,
						output = 0,
						cacheRead = 0,
						cacheWrite = 0,
						usdCost = 0;

					for (const e of ctx.sessionManager.getBranch()) {
						if (e.type === "message" && e.message.role === "assistant") {
							const m = e.message as AssistantMessage;
							input += m.usage.input ?? 0;
							output += m.usage.output ?? 0;
							cacheRead += m.usage.cacheRead ?? 0;
							cacheWrite += m.usage.cacheWrite ?? 0;
							usdCost += m.usage.cost?.total ?? 0;
						}
					}

					const r = rateFor(rates, ctx.model?.id);
					const credits =
						(input * r.input +
							cacheRead * r.cacheRead +
							cacheWrite * r.cacheWrite +
							output * r.output) /
						1_000_000;

					const branch = footerData.getGitBranch();
					const branchStr = branch ? ` (${branch})` : "";
					const modelStr = ctx.model?.id || "no-model";

					const tokens =
						`↑${fmt(input)}` +
						(cacheRead ? ` R${fmt(cacheRead)}` : "") +
						(cacheWrite ? ` W${fmt(cacheWrite)}` : "") +
						` ↓${fmt(output)}`;
					const creditStr = `C${fmtCredits(credits)}`;
					const usdStr = usdCost > 0 ? ` $${usdCost.toFixed(3)}` : "";

					const left = theme.fg("dim", `${tokens}  ${creditStr}${usdStr}`);
					const right = theme.fg("dim", `${modelStr}${branchStr}`);

					const pad = " ".repeat(
						Math.max(1, width - visibleWidth(left) - visibleWidth(right)),
					);
					return [truncateToWidth(left + pad + right, width)];
				},
			};
		});
	};

	pi.on("session_start", async (_event, ctx) => {
		if (enabled && ctx.hasUI) renderFooter(ctx);
	});

	pi.registerCommand("credits-footer", {
		description: "Toggle the AiCredits footer (default: on)",
		handler: async (_args, ctx) => {
			enabled = !enabled;
			if (enabled) {
				renderFooter(ctx);
				ctx.ui.notify("AiCredits footer enabled", "info");
			} else {
				ctx.ui.setFooter(undefined);
				ctx.ui.notify("AiCredits footer disabled (default footer restored)", "info");
			}
		},
	});

	pi.registerCommand("credits-rates", {
		description: "Show the AiCredits rate table currently in use",
		handler: async (_args, ctx) => {
			const lines = Object.entries(rates).map(
				([k, r]) =>
					`  ${k.padEnd(22)} input=${r.input}  cacheRead=${r.cacheRead}  cacheWrite=${r.cacheWrite}  output=${r.output}`,
			);
			ctx.ui.notify(`AiCredits rates (per 1M tokens):\n${lines.join("\n")}`, "info");
		},
	});
}
